(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Count - Min:
4
inf

Choose a navigation strategy:
[1] - SingleStepping
[2] - TopDown
[3] - HeaviestFirst
[4] - DivideAndQuery
> 1
Do you want to use provenance enhancement?  (y/n) y
How do you want to perform the enhancement?
[1] - Use the last print as criterion
[2] - Use a wrong output as criterion
[3] - Select node as criterion
> 1
Format: "pdf" not recognized. Use one of:
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 8, in main
    ConsoleInterface().run()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\console_interface.py", line 115, in run
    result_tree = nav.navigate()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 8, in navigate
    self.recursive_navigate(self.exec_tree.root_node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 16, in recursive_navigate
    self.recursive_navigate(c)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 16, in recursive_navigate
    self.recursive_navigate(c)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 17, in recursive_navigate
    self.evaluate(current_node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\navgiation_strategy.py", line 32, in evaluate
    self._interactive_evaluation(node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\navgiation_strategy.py", line 56, in _interactive_evaluation
    vis.view_exec_tree(str(id(node)))
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\visualization.py", line 51, in view_exec_tree
    self.graph.view()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 242, in view
    quiet=quiet, quiet_view=quiet_view)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 209, in render
    quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 184, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tpdf', '-O', '2607669475464.gv']' returned non-zero exit status 1. [stderr: b'Format: "pdf" not recognized. Use one of:\r\n']

(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>py dn.py
Pasta .noworkflow apagada

(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Count - Min:
4
inf

Choose a navigation strategy:
[1] - SingleStepping
[2] - TopDown
[3] - HeaviestFirst
[4] - DivideAndQuery
> 1
Do you want to use provenance enhancement?  (y/n) y
How do you want to perform the enhancement?
[1] - Use the last print as criterion
[2] - Use a wrong output as criterion
[3] - Select node as criterion
> 2
Tell me which output data is wrong
> inf
Format: "pdf" not recognized. Use one of:
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 8, in main
    ConsoleInterface().run()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\console_interface.py", line 115, in run
    result_tree = nav.navigate()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 8, in navigate
    self.recursive_navigate(self.exec_tree.root_node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 16, in recursive_navigate
    self.recursive_navigate(c)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 16, in recursive_navigate
    self.recursive_navigate(c)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 17, in recursive_navigate
    self.evaluate(current_node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\navgiation_strategy.py", line 32, in evaluate
    self._interactive_evaluation(node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\navgiation_strategy.py", line 56, in _interactive_evaluation
    vis.view_exec_tree(str(id(node)))
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\visualization.py", line 51, in view_exec_tree
    self.graph.view()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 242, in view
    quiet=quiet, quiet_view=quiet_view)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 209, in render
    quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 184, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tpdf', '-O', '1267564349192.gv']' returned non-zero exit status 1. [stderr: b'Format: "pdf" not recognized. Use one of:\r\n']

(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>py dn.py
Pasta .noworkflow apagada

(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Count - Min:
4
inf

Choose a navigation strategy:
[1] - SingleStepping
[2] - TopDown
[3] - HeaviestFirst
[4] - DivideAndQuery
> 1
Do you want to use provenance enhancement?  (y/n) y
How do you want to perform the enhancement?
[1] - Use the last print as criterion
[2] - Use a wrong output as criterion
[3] - Select node as criterion
> 3
Format: "pdf" not recognized. Use one of:
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 8, in main
    ConsoleInterface().run()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\console_interface.py", line 110, in run
    tmp_vis.view_exec_tree('tmp_tree')
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\visualization.py", line 51, in view_exec_tree
    self.graph.view()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 242, in view
    quiet=quiet, quiet_view=quiet_view)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 209, in render
    quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 184, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tpdf', '-O', 'tmp_tree.gv']' returned non-zero exit status 1. [stderr: b'Format: "pdf" not recognized. Use one of:\r\n']

(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>
